id: e6e598831b46440f807e424f5bddaac1
initial_creation_type: ocr
source_metadata:
  volumes:
    facd68d9665d444e83f75cd5b9e6e1af:
      base_file: v063.txt
      image_group_id: I1PD95909
      title: ''
      total_pages: 1902
      volume_number: 64
